on: [push]
name: Crawly CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Build the executable for Crawly."
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p crawly --release
      - name: "Run a search. (short version)"
        uses: actions-rs/cargo@v1
        with:
          command: run 
          args: -p crawly -- -i ./test/speech_annotated.xml -w "noun"
      - name: "Run a search. (long version)"
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p crawly -- --inf ./test/./test/speech_annotated.xml --wrd "noun"