on: [push]
name: XMLIFY CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Build the executable for XMLIFY."
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p xmlify --release
      - name: "Serialize a file. (short version)"
        uses: actions-rs/cargo@v1
        with:
          command: run --bin xmlify
          args: -- -i ./test/test.txt
      - name: "Serialize a file. (long version)"
        uses: actions-rs/cargo@v1
        with:
          command: run --bin xmlify
          args: -- --inf ./test/test.txt
