on: [push]
name: XMLIFY CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Build the executable for XMLIFY."
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p xmlify --release
      - name: "Serialize a file. (short version)"
        uses: actions-rs/cargo@v1
        with:
          command: run 
          args: -p xmlify -- -i ./test/speech.txt
      - name: "Serialize a file. (long version)"
        uses: actions-rs/cargo@v1
        with:
          command: run 
          args: -p xmlify -- --inf ./test/speech.txt
      - name: "Confirm success"
        run: "ls test"
